---
- name: Change the hostname
  hosts: veos
  gather_facts: no
  become: yes
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
  tasks:
    - name: run the hostname command
      arista.eos.eos_config:
        lines:
          - 'hostname rumplestiltskin'
