---
- name: Play to show the software version on an Arista switch
  hosts: veos
  gather_facts: no
  connection: network_cli

  tasks:
  - name: Import encrypted credentials
    include_vars: secrets_encrypted.yaml

  - name: Gather version from switches
    eos_command:
      commands:
        - 'show version | include Software'
    register: showvers

  - name: Print first line of the stdout array
    debug: var=showvers.stdout[0]
