vlans:
  - name: vlan 1234
    description:		"[UNI] Panopticon"
    port_type: 		svi
    ip_address:		87.44.43.2/28
    ipv6_address:		2001:770:6:1705::1/64
    ip_helper_address:
      - address: 87.44.1.23
      - address: 87.44.4.56
#
    vrrp_group:		1
    vrrp_ip:			87.44.43.1
    vrrp_priority:		60
    vrrp_auth:			sooper_seekrit
    vrrp_preempt:		True
#
    shutdown:			False
    default:			False
