---
- name: Play 1 - Show the software version on an Arista switch
  hosts: veos
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
  tasks:
    - name: Task 1.1 - Gather version from switches
      eos_command:
        commands:
          - 'show version | include Software'
          - 'show uptime'
      register: eos_commands

    - name: Task 1.2 - Print output
      debug: var=eos_commands.stdout_lines

